version: '3.8'

services:
  airflow:
    build: .
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW_HOME=/usr/local/airflow
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./include:/usr/local/airflow/include
      - ./config:/usr/local/airflow/config
      - ./.env:/usr/local/airflow/.env
    ports:
      - "8080:8080"
    command: standalone